version: '3.8'

services:
  matematicas-andinas:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    restart: unless-stopped
